replicaCount: 2

image:
  repository: <your-dockerhub-username>/productservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: productservice-ingress
  path: /
  hosts:
    - host: productservice.example.com
      paths:
        - /
  tls: []
